# Generated by Django 6.0.6 on 2026-06-29 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anno_images', '0001_initial'),
        ('anno_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique slug per project, e.g. 'worker_finish'.", max_length=64)),
                ('display_name', models.CharField(help_text="Human-readable label, e.g. 'Worker Finish'.", max_length=128)),
                ('color', models.CharField(default='#6366F1', help_text="Hex color code for UI badges, e.g. '#22C55E'.", max_length=7)),
                ('description', models.TextField(blank=True, default='', help_text="Optional explanation of this tag's meaning.")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tags are hidden from the apply UI but remain on existing images.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='anno_projects.project')),
            ],
            options={
                'verbose_name': 'project tag',
                'verbose_name_plural': 'project tags',
                'db_table': 'anno_project_tag',
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='', help_text="Optional comment, e.g. explanation for a 'worker question' tag.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_image_tags', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='anno_images.image2d')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='anno_tags.projecttag')),
            ],
            options={
                'verbose_name': 'image tag',
                'verbose_name_plural': 'image tags',
                'db_table': 'anno_image_tag',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image'], name='anno_image__image_i_b581a7_idx'), models.Index(fields=['tag'], name='anno_image__tag_id_b79d88_idx')],
                'unique_together': {('image', 'tag')},
            },
        ),
    ]
