# Generated by Django 6.0.6 on 2026-07-14 01:43

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_images', '0002_operation_source_and_more'),
        ('anno_projects', '0001_initial'),
        ('anno_tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetag',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at'], 'verbose_name': 'image tag', 'verbose_name_plural': 'image tags'},
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name': 'project tag', 'verbose_name_plural': 'project tags'},
        ),
        migrations.AlterModelManagers(
            name='imagetag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='projecttag',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='imagetag',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='imagetag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('image', 'tag'), name='uniq_active_image_tag'),
        ),
        migrations.AddConstraint(
            model_name='projecttag',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'name'), name='uniq_active_project_tag_name'),
        ),
    ]
