# Generated by Django 6.0.6 on 2026-07-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_tags', '0002_alter_imagetag_options_alter_projecttag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttag',
            name='permission_level',
            field=models.CharField(choices=[('common', 'Common'), ('worker', 'Worker'), ('supervisor', 'Supervisor')], default='common', help_text="Which project role may apply this tag: 'common' = any member; 'worker'/'supervisor' = only that role.", max_length=20),
        ),
    ]
