# Generated by Django 6.0.6 on 2026-06-25 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('meta_info', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata about the dataset content.')),
                ('label_mapping', models.JSONField(blank=True, default=dict, help_text="Semantic label names to numeric class IDs, e.g. {'cat': 0, 'dog': 1}.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'anno_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'gpu-box-01'.", max_length=255)),
                ('prefix', models.CharField(db_index=True, help_text='Non-secret leading segment of the token, for lookup and display.', max_length=12)),
                ('key_hash', models.CharField(help_text='SHA-256 hex digest of the full token. The plaintext is never stored.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='anno_projects.project')),
            ],
            options={
                'verbose_name': 'project API key',
                'verbose_name_plural': 'project API keys',
                'db_table': 'anno_project_api_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='anno_projec_project_fa865c_idx'), models.Index(fields=['prefix'], name='anno_projec_prefix_aa66bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('supervisor', 'Supervisor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='added_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='anno_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project membership',
                'verbose_name_plural': 'project memberships',
                'db_table': 'anno_project_membership',
                'ordering': ['created_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
