# Generated by Django 6.0.6 on 2026-06-25 06:48

import anno_images.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anno_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('polygon', 'Polygon'), ('box', 'Box'), ('keypoint', 'Keypoint')], max_length=20)),
                ('label', models.IntegerField(blank=True, help_text='Numeric classification label (references Project.label_mapping).', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the current version of the annotation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Denormalized FK for fast project-scoped queries.', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='anno_projects.project')),
            ],
            options={
                'verbose_name': 'annotation 2D',
                'verbose_name_plural': 'annotations 2D',
                'db_table': 'anno_annotation_2d',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Box2D',
            fields=[
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='box', serialize=False, to='anno_images.annotation2d')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('rotation', models.FloatField(blank=True, default=0.0, help_text='Rotation angle in degrees clockwise.', null=True)),
            ],
            options={
                'verbose_name': 'box 2D',
                'verbose_name_plural': 'boxes 2D',
                'db_table': 'anno_box_2d',
            },
        ),
        migrations.CreateModel(
            name='Keypoint2D',
            fields=[
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='keypoint', serialize=False, to='anno_images.annotation2d')),
                ('points', models.JSONField(help_text='List of keypoint coordinates as [[x1,y1], [x2,y2], ...].')),
            ],
            options={
                'verbose_name': 'keypoint 2D',
                'verbose_name_plural': 'keypoints 2D',
                'db_table': 'anno_keypoint_2d',
            },
        ),
        migrations.CreateModel(
            name='Polygon2D',
            fields=[
                ('annotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='polygon', serialize=False, to='anno_images.annotation2d')),
                ('points', models.JSONField(help_text='List of polygon vertices as [[x1,y1], [x2,y2], ...].')),
            ],
            options={
                'verbose_name': 'polygon 2D',
                'verbose_name_plural': 'polygons 2D',
                'db_table': 'anno_polygon_2d',
            },
        ),
        migrations.CreateModel(
            name='Image2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=anno_images.models._image_upload_to)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='anno_projects.project')),
            ],
            options={
                'verbose_name': 'image 2D',
                'verbose_name_plural': 'images 2D',
                'db_table': 'anno_image_2d',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='annotation2d',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='anno_images.image2d'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('modify', 'Modify'), ('delete', 'Delete')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_annotation', models.ForeignKey(blank=True, help_text="The annotation before the change (null for 'add' operations).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_from', to='anno_images.annotation2d')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='anno_images.image2d')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('to_annotation', models.ForeignKey(blank=True, help_text="The annotation after the change (null for 'delete' operations).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_as_to', to='anno_images.annotation2d')),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
                'db_table': 'anno_operation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='annotation2d',
            index=models.Index(fields=['image', 'is_active'], name='anno_annota_image_i_ed1719_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation2d',
            index=models.Index(fields=['image', 'annotation_type', 'is_active'], name='anno_annota_image_i_910390_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation2d',
            index=models.Index(fields=['project', 'is_active'], name='anno_annota_project_5a5f06_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['image', 'created_at'], name='anno_operat_image_i_9c1fea_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['from_annotation'], name='anno_operat_from_an_bc4ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['to_annotation'], name='anno_operat_to_anno_366b7a_idx'),
        ),
    ]
