# Generated by Django 6.0.6 on 2026-07-01 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='source',
            field=models.CharField(choices=[('human', 'Human'), ('inference', 'Inference'), ('interactive', 'Interactive')], db_index=True, default='human', help_text='Origin of the operation: human, inference or interactive.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['source', 'to_annotation'], name='anno_operat_source_697088_idx'),
        ),
    ]
