# Generated by Django 6.0.6 on 2026-07-15 03:10

import anno_exports.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anno_projects', '0002_alter_project_options_alter_projectapikey_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('format', models.CharField(choices=[('coco', 'COCO JSON'), ('yolo', 'YOLO')], max_length=10)),
                ('include_images', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, default=None, help_text='When the export file should be cleaned up (null = never expire).', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_tasks', to='anno_projects.project')),
            ],
            options={
                'db_table': 'anno_export_task',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExportTaskResult',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='result', serialize=False, to='anno_exports.exporttask')),
                ('export_file', models.FileField(blank=True, default=None, null=True, upload_to=anno_exports.models._export_upload_to)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anno_export_task_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['project', 'status'], name='anno_export_project_3d8c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='exporttask',
            index=models.Index(fields=['status', 'expires_at'], name='anno_export_status_6962c0_idx'),
        ),
    ]
