# Generated by Django 6.0.6 on 2026-07-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anno_exports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttask',
            name='completed_items',
        ),
        migrations.RemoveField(
            model_name='exporttask',
            name='total_items',
        ),
    ]
