# Generated by Django 6.0.6 on 2026-06-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anno_images', '0001_initial'),
        ('anno_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'SAM-2 box->mask'.", max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('inference_url', models.URLField(help_text="The service's predict endpoint.", max_length=1024)),
                ('supported_result_types', models.JSONField(default=list, help_text="Subset of {'polygon','box','keypoint'} this service can return.")),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('header', 'Header'), ('query', 'Query param')], default='none', max_length=10)),
                ('auth_param_name', models.CharField(blank=True, default='', help_text="Header name (e.g. 'Authorization', 'X-API-Key') or query key (e.g. 'api_key').", max_length=128)),
                ('auth_secret', models.CharField(blank=True, default='', help_text='Plaintext credential value presented to the service. Never serialized in API output.', max_length=512)),
                ('timeout_seconds', models.PositiveIntegerField(default=60, help_text='Per-image HTTP timeout when calling the service.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inference_providers', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Null => global provider usable by any project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inference_providers', to='anno_projects.project')),
            ],
            options={
                'db_table': 'anno_inference_provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('annotations_created', models.PositiveIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_jobs', to='anno_projects.project')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='anno_infers.inferenceserviceprovider')),
            ],
            options={
                'db_table': 'anno_inference_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('annotations_created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_job_items', to='anno_images.image2d')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='anno_infers.inferencejob')),
            ],
            options={
                'db_table': 'anno_inference_job_item',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job', 'status'], name='anno_infere_job_id_f2661d_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'image'), name='uniq_job_image')],
            },
        ),
        migrations.AddIndex(
            model_name='inferenceserviceprovider',
            index=models.Index(fields=['project', 'is_active'], name='anno_infere_project_c78daa_idx'),
        ),
        migrations.AddIndex(
            model_name='inferenceserviceprovider',
            index=models.Index(fields=['is_active'], name='anno_infere_is_acti_55ee4d_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['project', 'status'], name='anno_infere_project_fcf365_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencejob',
            index=models.Index(fields=['status', 'created_at'], name='anno_infere_status_56edb2_idx'),
        ),
    ]
