# Generated by Django 6.0.6 on 2026-07-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_images', '0002_operation_source_and_more'),
        ('anno_infers', '0001_initial'),
        ('anno_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_index', models.PositiveIntegerField(help_text="Position of this result in the model's returned list.")),
                ('result_type', models.CharField(choices=[('polygon', 'Polygon'), ('box', 'Box'), ('keypoint', 'Keypoint')], max_length=20)),
                ('label', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text="Normalized geometry, e.g. {'points': [...]} or box fields.")),
                ('raw_result', models.JSONField(blank=True, default=dict, help_text="The model's raw returned result.")),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('committed', 'Committed'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anno_inference_result',
                'ordering': ['task_id', 'result_index'],
            },
        ),
        migrations.CreateModel(
            name='InferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict, help_text='Provider config snapshot at creation time (never includes auth_secret).')),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('annotations_created', models.PositiveIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anno_inference_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InferenceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('annotations_created', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anno_inference_task',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveInferenceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.PositiveIntegerField(help_text='Step number within the session, from 1.')),
                ('prompt', models.JSONField(blank=True, default=dict, help_text='The prompts the user supplied this step.')),
                ('result', models.JSONField(blank=True, default=dict, help_text='Summary of the model output, e.g. score / bbox / area.')),
                ('result_type', models.CharField(blank=True, choices=[('polygon', 'Polygon'), ('box', 'Box'), ('keypoint', 'Keypoint')], default='', max_length=20)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text="Normalized candidate geometry, e.g. {'points': [...]}.")),
                ('raw_result', models.JSONField(blank=True, default=dict, help_text="The service's raw returned result.")),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anno_interactive_operation',
                'ordering': ['session_id', 'step_index'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveInferenceServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human label, e.g. 'SAM-2 interactive'.", max_length=255)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('inference_url', models.URLField(help_text="The service's predict endpoint.", max_length=1024)),
                ('supported_prompt_types', models.JSONField(default=list, help_text="Subset of {'box','positive_point','negative_point','mask','text'} accepted.")),
                ('supported_result_types', models.JSONField(default=list, help_text="Subset of {'polygon','box','keypoint'} this service can return.")),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('header', 'Header'), ('query', 'Query param')], default='none', max_length=10)),
                ('auth_param_name', models.CharField(blank=True, default='', help_text="Header name (e.g. 'Authorization', 'X-API-Key') or query key (e.g. 'api_key').", max_length=128)),
                ('auth_secret', models.CharField(blank=True, default='', help_text='Plaintext credential value presented to the service. Never serialized in API output.', max_length=512)),
                ('timeout_seconds', models.PositiveIntegerField(default=60, help_text='Per-step HTTP timeout when calling the service.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anno_interactive_inference_provider',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveInferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('editing', 'Editing'), ('committed', 'Committed'), ('discarded', 'Discarded'), ('failed', 'Failed')], db_index=True, default='editing', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anno_interactive_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='inferencejob',
            name='anno_infere_project_fcf365_idx',
        ),
        migrations.RemoveIndex(
            model_name='inferencejob',
            name='anno_infere_status_56edb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='inferencejobitem',
            name='anno_infere_job_id_f2661d_idx',
        ),
        migrations.RemoveConstraint(
            model_name='inferencejobitem',
            name='uniq_job_image',
        ),
        migrations.AddField(
            model_name='inferenceresult',
            name='annotation',
            field=models.OneToOneField(blank=True, help_text='The Annotation2D this result was committed as (null until committed).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inference_result', to='anno_images.annotation2d'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inference_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_runs', to='anno_projects.project'),
        ),
        migrations.AddField(
            model_name='inferencerun',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='anno_infers.inferenceserviceprovider'),
        ),
        migrations.AddField(
            model_name='inferencetask',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inference_tasks', to='anno_images.image2d'),
        ),
        migrations.AddField(
            model_name='inferencetask',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='anno_infers.inferencerun'),
        ),
        migrations.AddField(
            model_name='inferenceresult',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='anno_infers.inferencetask'),
        ),
        migrations.AddField(
            model_name='interactiveinferenceserviceprovider',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_interactive_inference_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactiveinferenceserviceprovider',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Null => global provider usable by any project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_inference_providers', to='anno_projects.project'),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='final_annotation',
            field=models.ForeignKey(blank=True, help_text='The committed annotation (null until committed); reverse-lookup target.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_session', to='anno_images.annotation2d'),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='from_annotation',
            field=models.ForeignKey(blank=True, help_text='Original annotation when refining an existing one (null for new).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_sessions_as_from', to='anno_images.annotation2d'),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_inference_sessions', to='anno_images.image2d'),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactive_inference_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_inference_sessions', to='anno_projects.project'),
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='anno_infers.interactiveinferenceserviceprovider'),
        ),
        migrations.AddField(
            model_name='interactiveinferenceoperation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='anno_infers.interactiveinferencesession'),
        ),
        migrations.RemoveField(
            model_name='inferencejob',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inferencejob',
            name='project',
        ),
        migrations.RemoveField(
            model_name='inferencejob',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='inferencejobitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='inferencejobitem',
            name='job',
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['project', 'status'], name='anno_infere_project_e81f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencerun',
            index=models.Index(fields=['status', 'created_at'], name='anno_infere_status_7532d2_idx'),
        ),
        migrations.AddIndex(
            model_name='inferencetask',
            index=models.Index(fields=['run', 'status'], name='anno_infere_run_id_51b59f_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferencetask',
            constraint=models.UniqueConstraint(fields=('run', 'image'), name='uniq_run_image'),
        ),
        migrations.AddIndex(
            model_name='inferenceresult',
            index=models.Index(fields=['task', 'status'], name='anno_infere_task_id_e63b59_idx'),
        ),
        migrations.AddConstraint(
            model_name='inferenceresult',
            constraint=models.UniqueConstraint(fields=('task', 'result_index'), name='uniq_task_result_index'),
        ),
        migrations.AddIndex(
            model_name='interactiveinferenceserviceprovider',
            index=models.Index(fields=['project', 'is_active'], name='anno_intera_project_682280_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveinferenceserviceprovider',
            index=models.Index(fields=['is_active'], name='anno_intera_is_acti_3ccca9_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveinferencesession',
            index=models.Index(fields=['project', 'status'], name='anno_intera_project_d97309_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveinferencesession',
            index=models.Index(fields=['final_annotation'], name='anno_intera_final_a_8f8210_idx'),
        ),
        migrations.AddIndex(
            model_name='interactiveinferenceoperation',
            index=models.Index(fields=['session', 'step_index'], name='anno_intera_session_547c28_idx'),
        ),
        migrations.AddConstraint(
            model_name='interactiveinferenceoperation',
            constraint=models.UniqueConstraint(fields=('session', 'step_index'), name='uniq_session_step_index'),
        ),
        migrations.DeleteModel(
            name='InferenceJob',
        ),
        migrations.DeleteModel(
            name='InferenceJobItem',
        ),
    ]
