# Generated by Django 6.0.6 on 2026-07-07 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_images', '0002_operation_source_and_more'),
        ('anno_infers', '0002_inferenceresult_inferencerun_inferencetask_and_more'),
        ('anno_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interactiveinferencesession',
            name='anno_intera_final_a_8f8210_idx',
        ),
        migrations.RenameField(
            model_name='interactiveinferencesession',
            old_name='final_annotation',
            new_name='to_annotation',
        ),
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='interactiveinferencesession',
            index=models.Index(fields=['to_annotation'], name='anno_intera_to_anno_711082_idx'),
        ),
        migrations.RemoveField(
            model_name='interactiveinferencesession',
            name='committed_at',
        ),
        migrations.RemoveField(
            model_name='interactiveinferencesession',
            name='discarded_at',
        ),
    ]
