# Generated by Django 6.0.6 on 2026-07-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0003_remove_interactiveinferencesession_anno_intera_final_a_8f8210_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveinferencesession',
            name='session_token',
            field=models.CharField(blank=True, default=None, help_text='Short-lived token the service minted for browser→service calls. NULL until the handshake succeeds; unique thereafter.', max_length=128, null=True, unique=True),
        ),
    ]
