# Generated by Django 6.0.6 on 2026-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_images', '0001_initial'),
        ('anno_infers', '0004_interactiveinferencesession_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveinferenceoperation',
            name='annotation',
            field=models.ForeignKey(blank=True, help_text='The Annotation2D created by this operation step (null until committed).', null=True, on_delete=models.SET_NULL, related_name='interactive_operations', to='anno_images.annotation2d'),
        ),
    ]
