# Generated by Django 6.0.6 on 2026-07-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0005_interactiveinferenceoperation_annotation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interactiveinferencesession',
            name='anno_intera_to_anno_711082_idx',
        ),
        migrations.RemoveField(
            model_name='interactiveinferencesession',
            name='from_annotation',
        ),
        migrations.RemoveField(
            model_name='interactiveinferencesession',
            name='to_annotation',
        ),
    ]
