# Generated by Django 6.0.6 on 2026-07-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0006_remove_from_to_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveinferenceserviceprovider',
            name='max_concurrency',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of concurrent interactive sessions. 0 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='interactiveinferencesession',
            name='status',
            field=models.CharField(choices=[('editing', 'Editing'), ('discarded', 'Discarded'), ('failed', 'Failed')], db_index=True, default='editing', max_length=12),
        ),
    ]
