# Generated by Django 6.0.6 on 2026-07-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0007_provider_max_concurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveinferenceserviceprovider',
            name='max_concurrency',
        ),
    ]
