# Generated by Django 6.0.6 on 2026-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0008_remove_max_concurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceserviceprovider',
            name='inference_url',
            field=models.URLField(help_text="The service's base URL (e.g., https://infer.example.com). The platform appends standard SDK paths (/predict, /session, etc.) automatically.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='interactiveinferenceserviceprovider',
            name='inference_url',
            field=models.URLField(help_text="The service's base URL (e.g., https://infer.example.com). The platform appends standard SDK paths (/predict, /session, etc.) automatically.", max_length=1024),
        ),
    ]
