# Generated by Django 6.0.6 on 2026-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0009_alter_inferenceserviceprovider_inference_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveinferenceserviceprovider',
            name='public_url',
            field=models.CharField(blank=True, default='', help_text="Browser-reachable base URL for the frontend's direct predict calls, e.g. '/_interactive_infer' (a same-origin path the reverse proxy forwards to the service) or 'https://host/_interactive_infer'. Distinct from inference_url, which is the server-side address used for the handshake. Blank => fall back to the service handshake, then inference_url.", max_length=1024),
        ),
    ]
