# Generated by Django 6.0.6 on 2026-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anno_infers', '0010_interactiveinferenceserviceprovider_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceserviceprovider',
            name='inference_url',
            field=models.CharField(help_text="The service's base URL (e.g., https://infer.example.com or http://anno-sam:8422 for an internal Docker service). The platform appends standard SDK paths (/predict, /session, etc.) automatically.", max_length=1024),
        ),
        migrations.AlterField(
            model_name='interactiveinferenceserviceprovider',
            name='inference_url',
            field=models.CharField(help_text="The service's base URL (e.g., https://infer.example.com or http://anno-sam:8422 for an internal Docker service). The platform appends standard SDK paths (/predict, /session, etc.) automatically.", max_length=1024),
        ),
    ]
